### ISSUE TITLE
Code Review session

### ISSUE THREAD

**Issue by manuelmrm** [ramarty/covid-social-media-analysis#4]
# Data cleaning code review checklist

## List of files to be checked 
- 02_clean_crosstate_data
- 07_Cross_State_Analysis
- Output in 07_Cross_State_Analysis.html

In addition, for most recent cleaning and analysis, the following files can also be reviewed:
- 02_clean_crosstate_bidaily
- 09_Crosstate_Bidaily_Analysis
- Output in 09_Crosstate_Bidaily_Analysis.html

## Context
This project started very recently and is ongoing. I have been working relatively fast on the code, and I would like to make sure that both the code and the content makes sense. Comments on how to improve the clarity, organization or reproducibility of the code are welcome. 

For now, the code is mostly done in Rmarkdown with the goal of producing HTMLs that include both the code and the graphs in one spot. The final output will be a dashboard, which implies that there is no need for a master file to produce the graphs. Nonetheless, I've added a master file to run the code - I'm working on it to produce the HTMLs as well. Finally, in order to knit the document, I am loading the packages in every file (required by rmd). 

# DIME Analytics Checklist 

Not everything might apply to this project I believe. 

## Reproducibility
 All the outputs are recreated and are exactly the same as the ones shared by the coder
 Includes a master script
 Master script clearly indicates which line needs to be changed to run in a different computer
 The master script runs from start to end if the reviewer changes only directory path(s) in one
location of the master script
 The master script installs any commands required (e.g. from SSC in Stata, CRAN in R, etc.)

## Code organization and readability
 Code names are informative
 It is clear in the code why tasks are being executed
 The code structure facilitates understanding of the tasks
 Code uses white space to improve readability
 There is extensive use of comments to explain the code
 The code is efficient (tasks are executed in the simplest way possible, loops are used when needed rather than repeating lines, pre-defined functions are used)
 Common tasks are abstracted and automated (e.g. using functions or macros)

## Analysis scripts
 No variables are created in analysis scripts unless very specific to a particular output
 Code is modular
 Research decisions are well documented in the code (e.g. sample used, treatment of missing variables)
 The code implements the models described in the documentation
 The functions used are apropriate for the analysis being performed
 Categorical variables are used correctly (i.e., labeled integers are not used as continuous variables)
 Outputs are exported in a reproducible manner, and manual formatting is very limited

**Comment by ramarty** [comment]
I typed comments in word and there were formatting issues that I'm too lazy to resolve when transferring over here

[code_review.docx](https://github.com/ramarty/covid-social-media-analysis/files/4663538/code_review.docx)
